---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
- name: default
  run_list:
  - recipe[ztrustee::default]
- name: server
  run_list:
  - recipe[ztrustee::server]
  - recipe[ztrustee_test]
  attributes:
    postgresql:
      password:
        postgres: postgres
    ztrustee:
      repo_username: <%= ENV['ZTRUSTEE_REPO_USERNAME'] %>
      repo_password: <%= ENV['ZTRUSTEE_REPO_PASSWORD'] %>
      database:
        password: postgres

